### ISSUE TITLE
feature - Update GCM to FCM 

### ISSUE THREAD

**Issue by SjoerdvGestel** [Notificare/notificare-mvn-repo#3]
Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

https://firebase.google.com/docs/cloud-messaging/

**Comment by silentjohnny** [comment]
In case of using Notificare for push notifications, FCM does not add anything, as a matter of fact, it is just a rebranded GCM. If we would replace the current calls with FCM call, it would break compatibility with older builds, so we are postponing this. Needless to say, our SDK is tested with the latest version of GooglePlayServices.

**Comment by SjoerdvGestel** [comment]
thanks for the quick reply :+1:
