### ISSUE TITLE
SQLiteException in apps updated from v1.8.1 to v1.8.4

### ISSUE THREAD

**Issue by SjoerdvGestel** [Notificare/notificare-mvn-repo#4]
Fatal Exception: java.lang.RuntimeException: Unable to create application com.app.MyApplication: android.database.sqlite.SQLiteException: duplicate column name: pass_type (code 1): , while compiling: ALTER TABLE passes ADD COLUMN pass_type TEXT

Caused by android.database.sqlite.SQLiteException
android.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
android.database.sqlite.SQLiteDatabase.execSQL (SQLiteDatabase.java:1605)
re.notifica.database.NotificareDbHelper.upgradeV5V6 (NotificareDbHelper.java:155)
re.notifica.database.NotificareDbHelper.upgradeDb (NotificareDbHelper.java:120)
re.notifica.database.NotificareDbHelper.onUpgrade (NotificareDbHelper.java:96)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:256)
android.database.sqlite.SQLiteOpenHelper.getReadableDatabase (SQLiteOpenHelper.java:187)
re.notifica.NotificareInboxManager.load (NotificareInboxManager.java:70)
re.notifica.NotificareInboxManager.<init> (NotificareInboxManager.java:59)
re.notifica.Notificare.launch (Notificare.java:1917)
com.app.MyApplication.onCreate (MyApplication.java:42)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1036)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:618)

**Comment by SjoerdvGestel** [comment]
Fatal Exception: java.lang.RuntimeException: Unable to create application com.afrogleap.refugeebuddy.RefugeeBuddyApplication: android.database.sqlite.SQLiteException: duplicate column name: pass_type (code 1): , while compiling: ALTER TABLE passes ADD COLUMN pass_type TEXT

**Comment by silentjohnny** [comment]
That should not happen when upgrading from DB version 5 to 6 in a running application, since in version 5 there is no pass_type column. 
To be sure: this was an installed app built against Notificare SDK 1.8.1 and it was updated with a build against 1.8.4? 

What I find weird about the stack trace is: your app is called com.app.MyApplication and not  RefugeeBuddyApplication. Is this a test run or a real launch on a device?

**Comment by SjoerdvGestel** [comment]
@silentjohnny  i've tried to normalize the stack trace so it does not contain any trace of client data.

the trace comes from a recent released version of the app, it could be that uses skipped updates but accepted this one but i can't validate that statement at this time.

**Comment by SjoerdvGestel** [comment]
it could be that the previous version releases used v1.7.0

**Comment by silentjohnny** [comment]
Release 1.8.5 solves this exception
