### ISSUE TITLE
play services 12.0.1

### ISSUE THREAD

**Issue by kvolkers** [Notificare/notificare-mvn-repo#7]
I need to update play services due to an issue, but the notificare library is still using play services **12.0.0**. Unfortunately **12.0.0** contains a permissions bug that prevents us from using it.

This permission bug is fixed in play services **12.0.1**. Do you have an estimate for a release that uses this newer version?

**Comment by silentjohnny** [comment]
Yes, will be there this week!

**Comment by silentjohnny** [comment]
@kvolkers Good news! Release 1.13.5 passed tests, please update your Gradle config to use this new version.

**Comment by kvolkers** [comment]
@silentjohnny Perfect, thanks for the swift response!
